language: go

go:
  - "1.13"

env:
  - IMAGE_NAME=rdma/k8s-rdma-shared-dev-plugin

before_script:
  - go get github.com/mattn/goveralls

script:

  - make lint
  - sudo -E env "PATH=$PATH" make test
  - sudo -E env "PATH=$PATH" make test-coverage
  - for pkg in `ls test/coverage/*.cover`; do goveralls -coverprofile=$pkg -service=travis-ci; done
  - make build
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh $IMAGE_NAME latest $TRAVIS_CPU_ARCH
    on:
      branch: master
  # Push image to Dockerhub on tag
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh $IMAGE_NAME $TRAVIS_TAG $TRAVIS_CPU_ARCH
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
